### ISSUE TITLE
best practice(s) 的翻译统一

### ISSUE THREAD

**Issue by y2-Whyto** [FuchsiaOS/FuchsiaOS-docs-zh_CN#108]
根据已有谷歌相关产品文档中的翻译，现征求大家的翻译意见。

下列是谷歌产品文档中出现的“best practices”翻译：
- [Google Ads 帮助](https://support.google.com/google-ads/answer/6154846?hl=zh-Hans)（[原文](https://support.google.com/google-ads/answer/6154846?hl=en)）：**最佳做法**
- [Google Workspace 学习中心](https://support.google.com/a/users/answer/181242?hl=zh-Hans)（[原文](https://support.google.com/a/users/answer/181242?hl=en)）：**最佳做法**
- [Google 搜索中心](https://developers.google.com/search/docs/advanced/appearance/web-stories-creation-best-practices?hl=zh-cn)（[原文](https://developers.google.com/search/docs/advanced/appearance/web-stories-creation-best-practices?hl=en-us)）：**最佳做法**
- [Google Cloud](https://cloud.google.com/network-connectivity/docs/vpn/concepts/best-practices?hl=zh-cn)：（[原文](https://cloud.google.com/network-connectivity/docs/vpn/concepts/best-practices?hl=en-us)）：**最佳做法**
- [Android](https://developer.android.com/topic/google-play-instant/best-practices/games?hl=zh-cn)（[原文](https://developer.android.com/topic/google-play-instant/best-practices/games?hl=en-us)）：**最佳做法**
- ……

更多文档示例可以使用 Google 搜索关键字“谷歌 最佳做法”，由于案例较多，在此不再列举。

而使用关键词“谷歌 最佳实践”，则未能发现谷歌官方文档的结果。但民间多有使用。

两种翻译方式在其他公司的文档中也均有使用。

请大家就这两种翻译进行投票。

**Comment by y2-Whyto** [comment]
最佳做法

**Comment by y2-Whyto** [comment]
最佳实践

**Comment by n0b8d1** [comment]
个人以前听说过的是“最佳实践”，不过看到 Dongchan 和 Whyto 的介绍，觉得“最佳做法”可能更合适，也确实和 Google 其他文档保持一致。

**Comment by bootingman** [comment]
> 个人以前听说过的是“最佳实践”，不过看到 Dongchan 和 Whyto 的介绍，觉得“最佳做法”可能更合适，也确实和 Google 其他文档保持一致。

+1
