### ISSUE TITLE
关于系统更新中 Epoch 的翻译

### ISSUE THREAD

**Issue by RobiNexy** [FuchsiaOS/FuchsiaOS-docs-zh_CN#116]
原文：
`Epoch that the system cannot downgrade across via OTA. See[RFC-0071](/docs/contribute/governance/rfcs/0071_ota_backstop.md) for more context. `

描述：
epoch 直译是时代、纪元。按照RFC0071中的描述，epoch是指系统底层（例如文件系统）发生了重大改变的一次更新。在意义上也确实是指划时代的全新版本，但是一时之间找不到合适的汉语词汇，暂时译做 不能通过OTA跨纪元降级。

目前想到的词有纪元、大版本或者使用英文并注明epoch是指系统底层发生重大改变的版本，想听听大家意见。

**Comment by y2-Whyto** [comment]
第一句是原文完整的句子吗？感觉句法有点奇怪。
直接用“代”这个字翻译的话是什么效果？

**Comment by dongchany** [comment]
> 原文： `Epoch that the system cannot downgrade across via OTA. See[RFC-0071](/docs/contribute/governance/rfcs/0071_ota_backstop.md) for more context. `
> 
> 描述： epoch 直译是时代、纪元。按照RFC0071中的描述，epoch是指系统底层（例如文件系统）发生了重大改变的一次更新。在意义上也确实是指划时代的全新版本，但是一时之间找不到合适的汉语词汇，暂时译做 不能通过OTA跨纪元降级。
> 
> 目前想到的词有纪元、大版本或者使用英文并注明epoch是指系统底层发生重大改变的版本，想听听大家意见。

**Comment by dongchany** [comment]
我觉得使用英文并注明epoch是指系统底层发生重大改变的版本，这样的方案会更合适。
