### ISSUE TITLE
如何翻译专有名词 Product 和 Board

### ISSUE THREAD

**Issue by y2-Whyto** [FuchsiaOS/FuchsiaOS-docs-zh_CN#166]
Product 和 Board 是 Fuchsia 构建中的专有概念，在其他文档中没有记录，除了用于命令中，在编译相关的文档正文中也很常用。我在[去年翻译的相关文档](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/concepts/build_system/boards_and_products.md)中为其命名“产品”和“板型”，但没有发起 issue 进行通过。故特此创建 issue 与大家进行讨论。

- product 指构建的产物，为此形象地译为“产品”；
- board 指构建所面向的架构，如 x86-64 等。但原文没有使用“architecture”的名称，而是使用了“board”，故形象起见译为“板型”（注意**不是**“版型”）。

如果大家有更好的翻译方案，请在下方回复。如果认可某种翻译方式，请使用 👍 reaction。（右上角表情符号中）

**Comment by y2-Whyto** [comment]
产品和板型

**Comment by XuYicong** [comment]
产品和开发板

参考：https://source.android.com/setup/build/devices?hl=zh-cn
https://source.android.com/setup/build

**Comment by y2-Whyto** [comment]
> 产品和开发板
> 
> 
> 
> 参考：https://source.android.com/setup/build/devices?hl=zh-cn
> 
> https://source.android.com/setup/build

查看了一下，链接里的“开发板”是实体的板子，用于在特定硬件进行开发。本 issue 提出的翻译指的是“架构”，而非实体硬件，可能是团队借用了“开发板”的概念，但是含义似乎有所变化。

比如 x86-64 也被称为一种 board，这里直接成为开发板似乎不是很合适。

**Comment by ctzsm** [comment]
> 可能是团队借用了“开发板”的概念

https://cs.opensource.google/fuchsia/fuchsia/+/main:boards/ 是的这里是用了开发板的概念，延申到了虚拟设备也可以。

**Comment by XuYicong** [comment]
> 查看了一下，链接里的“开发板”是实体的板子，用于在特定硬件进行开发。本 issue 提出的翻译指的是“架构”，而非实体硬件，可能是团队借用了“开发板”的概念，但是含义似乎有所变化。
> 
> 比如 x86-64 也被称为一种 board，这里直接成为开发板似乎不是很合适。

含义确实有所变化。但board这个英文词的含义都能变，开发板这个中文词的含义也可以变。开发板在中文语境中本来也不仅指实体硬件，也可以指某一个型号或者某一类的开发板，用来表示“硬件种类”的概念不违和

这里我觉得英文的这个意思本身也是扩展出来的，也不是另立山头，中文如果翻译成不同的词，遇到英文词的意思处于模糊地带，或是在多个意思间跳变，甚至双关的情况，中文就抓瞎了

x86-64 称为一种开发板感觉挺合适的。如果感觉怪，其实英文里面感觉也是这么怪。但从构建工具的角度来看逻辑上确实该这么说。

**Comment by Lyrance** [comment]
感觉“板型”在汉语中出现频率低，以及可能会与“版型”有混淆
“开发板”的话乍一看可能有些奇怪，但是是常用词语，可以通过现有含义延伸理解

**Comment by y2-Whyto** [comment]
> 这个英文词的含义都能变，开发板这个中文词的含义也可以变。
>
> x86-64 称为一种开发板感觉挺合适的。如果感觉怪，其实英文里面感觉也是这么怪。但从构建工具的角度来看逻辑上确实该这么说。

词的含义可以变，但这是一个很漫长的过程。一个意思固定的词语要发生语意改变需要很多人的大量使用才行。开发文档不是流行文化，可能无法快速完成这种语意的迁移。

对于指代不同但内涵相同的情景，我认为翻译表达的调整并不是“另立山头”，而是根据自己的语言特点进行适应性的调整。**不同语言的灵活程度是不一样的，这跟习惯有关。** 英文中有些东西中文无法按照原来的成分进行翻译，反之亦然。因此不应该局限于一种固有的翻译。更何况已有的“开发板”和这里的 board 并不完全相同。

**Comment by XuYicong** [comment]
> 更何况已有的“开发板”和这里的 board 并不完全相同。

这里的“board”本身也是扩展后才有的意思，如果我们对“开发板”这个词也扩展它的意思，它们就相同了。“board”扩展之前和“开发板”本来也是相同的。
> 不同语言的灵活程度是不一样的

这确实。但每个人对一种语言的灵活程度的认识可能有主观差异。我觉得“开发板”这个词意思也没有偏离那么离谱，还在可以理解的范围内。
> 词的含义可以变，但这是一个很漫长的过程。一个意思固定的词语要发生语意改变需要很多人的大量使用才行。开发文档不是流行文化，可能无法快速完成这种语意的迁移。

我们作为开发文档，不可避免地会涉及到以前没有遇到过，没有人用过的概念，而不是要很多人用过的我们才能用。我们总是可以自行定义术语来满足表达需要。我们定义术语时将“开发板”的词义进行扩充，读者就能够理解我们的意思。
> 我认为翻译表达的调整并不是“另立山头”

我并不是说“翻译表达的调整是‘另立山头’”，之前表达可能不清楚。我其实是说，此处 board 词意的“变化”并不是这个词产生了新的意思，而只是原有意思的应用范围扩宽了。如果中文用另一个词翻译，就会有中间地带处于模凌两可的状态。如果遇到了意思介于两者之间的情况，中文的翻译就会有点麻烦。从实用的角度来说新造一个词不利于中文读者理解文义。

**Comment by y2-Whyto** [comment]
“产品”和“板型”译法已经达到了3个 👍，因此采用该翻译方式。并列入翻译术语表。
