### ISSUE TITLE
如何翻译术语 Moniker

### ISSUE THREAD

**Issue by y2-Whyto** [FuchsiaOS/FuchsiaOS-docs-zh_CN#171]
Moniker 在 Fuchsia 文档中是常用术语。在 2021 版文档中，我[将其翻译为“昵称”](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/concepts/diagnostics/lifecycle_events/README.md)。在 2022 版文档中，翻译到了该术语（#164）。

现就其译文进行投票。

moniker 的释义如下：

> (New Oxford American Dictionary) noun _informal_ : a name
>
> (牛津英汉汉英词典) noun _informal_ : 名字
>
> ([剑桥词典](https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%AE%80%E4%BD%93/moniker)) _noun_ [C] humorous (also **monicker**) : a name or nickname 名字；绰号
>
> ([韦氏词典](https://www.merriam-webster.com/dictionary/moniker)) noun _informal_ : NAME, NICKNAME

在微软文档的（部分）机器翻译中，将其译为“名字对象”。[\[1\]](https://docs.microsoft.com/zh-cn/windows/win32/com/item-monikers)[\[2\]](https://docs.microsoft.com/zh-cn/windows/win32/com/moniker-clients)

在 Google 上搜索时，搜索引擎将其与“name”关联。

如果赞同某种翻译，请使用 👍 reaction。如有其他推荐的翻译，请在下方回复。

**Comment by y2-Whyto** [comment]
昵称

**Comment by y2-Whyto** [comment]
绰号

**Comment by y2-Whyto** [comment]
名字

**Comment by ctzsm** [comment]
感觉**名字**肯定不行，各个字典的英文解释都是informal name，翻译成名字失去了这一层含义。

**Comment by y2-Whyto** [comment]
> 感觉**名字**肯定不行，各个字典的英文解释都是informal name，翻译成名字失去了这一层含义。

informal 是用法描述。意思的话还是 name 或 nickname。可能类似于中文里加个儿化音（“名儿”）之类？（个人感觉）

**Comment by tabidachinokaze** [comment]
别名

**Comment by ctzsm** [comment]
我个人认为一般有如下对应关系

- name - 名字
- nickname - 昵称
- alias - 别名

moniker说实话我第一次见这个词，但是因为有前几个词的对应关系，所以我倾向于翻译为绰号。

**Comment by XuYicong** [comment]
代称

个人认为比较贴切的意译

**Comment by XuYicong** [comment]
外号

同绰号，但字更好写

**Comment by XuYicong** [comment]
花名

个人认为比较贴切的直译

**Comment by y2-Whyto** [comment]
> 花名
> 
> 个人认为比较贴切的直译

flower name 预警（）

这词不是很常用啊，还有“旧时妓院中妓女在接客时使用的名字”的意项（bushi）

**Comment by y2-Whyto** [comment]
顺带说一句，其实可以不局限于仅投一个选项。

**Comment by y2-Whyto** [comment]
> 我个人认为一般有如下对应关系
> 
> * name - 名字
> * nickname - 昵称
> * alias - 别名
> 
> moniker说实话我第一次见这个词，但是因为有前几个词的对应关系，所以我倾向于翻译为绰号。

我刚刚想到，name 应该翻译成名**称**，这样的话其实某种程度上可以和“名**字**”区分开。第一次出现的时候可以标注原文。当然这也是我个人的想法，不知道各位觉得怎样。

**Comment by XuYicong** [comment]
> flower name 预警（）
> 
> 这词不是很常用啊，还有“旧时妓院中妓女在接客时使用的名字”的意项（bushi）

笑死，就是阿里那个花名啊，应该不会有人联想到妓女吧
因为外号和昵称感觉是小孩子起的，翻译成nickname更合适，而moniker感觉更像是成人之间的，感觉更加疏离

**Comment by y2-Whyto** [comment]
“代称”意向已达到三赞，因此采纳。本 issue 至此关闭。 @XuYicong 麻烦提交一下翻译术语表的 PR 吧。
