### ISSUE TITLE
关于capability翻译

### ISSUE THREAD

**Issue by Lyrance** [FuchsiaOS/FuchsiaOS-docs-zh_CN#175]
最近的两个pr给出了两种不同的翻译

功能：get-started/_common/components/_organizing_intro.md
能力：get-started/_common/components/_declaring_manifests.md

**Comment by y2-Whyto** [comment]
能力

**Comment by y2-Whyto** [comment]
功能

**Comment by y2-Whyto** [comment]
@Lyrance 对于已有备选翻译，记得在下方给出评论，以便大家投票。

**Comment by y2-Whyto** [comment]
“能力”的翻译已经超过4票，故采纳此翻译。稍后我会更新翻译术语表。
