### ISSUE TITLE
如何翻译术语realm

### ISSUE THREAD

**Issue by wwvm** [FuchsiaOS/FuchsiaOS-docs-zh_CN#176]
根据剑桥英语字典解释：
an [area](https://dictionary.cambridge.org/dictionary/english-chinese-simplified/area) of [interest](https://dictionary.cambridge.org/dictionary/english-chinese-simplified/interest) or [activity](https://dictionary.cambridge.org/dictionary/english-chinese-simplified/activity)
（兴趣或活动的）界，领域，范围

例句：The role of public opinion in the realm of politics 翻译为“公共舆论在政界中的作用”，因此，realm可以翻译为某某领域，某某界

**Comment by y2-Whyto** [comment]
领域

**Comment by y2-Whyto** [comment]
界

**Comment by y2-Whyto** [comment]
范围

**Comment by y2-Whyto** [comment]
@wwvm 下次可以将备选项在下面评论出来，方便大家投票。

**Comment by y2-Whyto** [comment]
“领域”达到3票，故采用此翻译。稍后将在翻译术语表中更新。
