### ISSUE TITLE
如何翻译contribute changes

### ISSUE THREAD

**Issue by wwvm** [FuchsiaOS/FuchsiaOS-docs-zh_CN#188]
文档中挺多contribute changes的表达，从字眼上看，contribute有投稿，贡献之意，changes有更改、变更之意。
目前没有贴切的翻译，暂时翻译为“贡献更改”

**Comment by wwvm** [comment]
贡献更改

**Comment by y2-Whyto** [comment]
“贡献更改”达到3票，采用该翻译。之后会在翻译术语表中更新。
