### ISSUE TITLE
关于 node 的翻译

### ISSUE THREAD

**Issue by y2-Whyto** [FuchsiaOS/FuchsiaOS-docs-zh_CN#201]
老生常谈了。

node 是计算机网络、算法和数据结构中的常见术语。常见的两个翻译：

- 结点
- 节点

前者在各大教材中均广泛使用，作为术语出现；就我个人看过的教材而言，没有使用后一种写法的。

值得指出，奇怪的是，微软、Google 的文档中却常用“节点”的翻译。

现就 node 的翻译进行投票。请各位为支持的翻译给出 👍 reaction。

**补充更新：**

查询了[全国科学技术名词审定委员会](http://www.cnterm.cn/)的[术语在线](https://www.termonline.cn/)，[node 的规范用语是“结点”](https://www.termonline.cn/word/122114/1#s1)，供大家参考。当然最终还是按照大家投票意愿来决定。

**Comment by y2-Whyto** [comment]
结点

**Comment by y2-Whyto** [comment]
节点

**Comment by n0b8d1** [comment]
当然是“节点”，没见过什么教材里用的“结点”。

**Comment by y2-Whyto** [comment]
> 当然是“节点”，没见过什么教材里用的“结点”。

略举两例：

- 《计算机网络（第七版）》谢希仁编著
- 《2023年计算机网络考研复习指导》王道论坛组编

**Comment by y2-Whyto** [comment]
“节点”超过3票，采用此翻译。
