### ISSUE TITLE
关于某些单词是否可以保留，不翻译的提问。

### ISSUE THREAD

**Issue by Yur5n** [FuchsiaOS/FuchsiaOS-docs-zh_CN#4]
我在翻译过程中，遇到一些与句子独立的单词，觉得可以不用翻译。如，data , Context ,  hash ,read ,write ,client 等其他类似单词和短句。理由如下：一是部分单词含义与翻译内容不符；二是此种类似单词应该是开发人员所熟知并理解的，不需要做翻译，翻译不到反而导致理解错误；三是此类高频单词或短句需要被使用者所认识。 我在一些标题旁保留了英文（如，序列块-Index chunk），觉得这样做能在自己拿捏不准意思的时候便于阅读者自己理解。希望大家能提一下自己的意见，在此感谢！

**Comment by bootingman** [comment]
我觉得其实都可以，但是不管采取哪一种，应该统一风格。Yur5n 同学可否给一个sample，能看看具体的上下文，我们来做定夺和一致的约定

**Comment by Mr-Linus** [comment]
目前请参照[约定与术语表](https://github.com/servicemesher/istio-official-translation/issues/77)进行汉化翻译。
