### ISSUE TITLE
如何翻译专有名词 Archivist

### ISSUE THREAD

**Issue by y2-Whyto** [FuchsiaOS/FuchsiaOS-docs-zh_CN#58]
出现情况举例：

（下面的示例出现在 `/concepts/diagnostics/inspect/rust.md`）

- This library enables components to serve Inspect and make it available to the **Archivist** for collection.
- This library includes the convenient \`ArchiveReader\` which is useful for fetching Inspect data from an **archivist** in a test or in production.

（下面的示例出现在 `/concepts/diagnostics/logs/attribution.md`，且该词在该文档中大量出现）

- When a Fuchsia component wishes to write logs, it must obtain a connection to a \[\`fuchsia.logger.LogSink\`\]\[logsink-protocol\] in its environment, typically provided by an instance of the \[**Archivist**\].
- \[**Archivist**\] serves the \[\`fuchsia.sys.internal/LogConnectionListener\`\]\[listener-protocol\] to receive \`LogSink\` connections along with \[\`fuchsia.sys.internal/SourceIdentity\`\]\[source-identity\] metadata.
- Archivist receives \[Event\]s on this protocol similarly to \`LogConnectionListener\`, retrieving attribution metadata from the
\[ComponentDescriptor\] sent by Component Manager along with the \`LogSink\` channel's handle.

根据[剑桥词典](https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%AE%80%E4%BD%93/archivist)：

> a person whose job is to take care of archives. 档案保管员；档案员。

根据牛津英汉汉英词典（macOS 内置）：

> 档案保管员 dàng'àn bǎoguǎnyuán

谷歌翻译使用的字眼是“档案管理员”。

**我目前采用的翻译是“归档器”。**

请大家针对可能的翻译畅所欲言。

**Comment by y2-Whyto** [comment]
归档器

**Comment by n0b8d1** [comment]
赞同, 咱统一使用目前 whyto在用 的 "归档器" 吧

**Comment by n0b8d1** [comment]
Dongchan 新建了术语表, 已包含 "归档器"
 https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/glossary/README.md
