### ISSUE TITLE
如何翻译专有名词 ArchiveAccessor

### ISSUE THREAD

**Issue by y2-Whyto** [FuchsiaOS/FuchsiaOS-docs-zh_CN#68]
出现情况举例：
（下面的示例出现在 `/concepts/diagnostics/lifecycle_events/README.md`）
- Lifecycle events can be read through the **ArchiveAccessor**. Only the \`snapshot\` mode is supported.
- Each JSON object in the array is one event entry. Like other data types in **ArchiveAccessor**,
each object consists of several fields, although the contents of metadata and payload differ
from other sources.

谷歌翻译保留了原文（与大写合体有关）。

accessor 一词在 Java、JavaScript 领域的已有翻译有“存取器”、“访问器”等。

对于 access 的动词释义，根据[剑桥词典](https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%AE%80%E4%BD%93/access)：

> to open a computer file (= a collection of information stored on a computer) in order to look at or change information in it.
读取（电脑文档）。

对于 access 的动词释义，根据牛津英汉汉英词典（macOS 内置）：

> 1. (approach, enter) 进入 jìnrù
> 1. Computing 存取 cúnqǔ ‹data›; 访问 fǎngwèn ‹website›

如果翻译“to access a file”，[谷歌翻译](https://translate.google.cn/?sl=en&tl=zh-CN&text=to%20access%20a%20file&op=translate)使用了“访问”字眼。

**我目前采用的翻译是“档案访问器”。**

请大家针对可能的翻译畅所欲言。

**Comment by y2-Whyto** [comment]
档案访问器

我使用“访问”一词的主要原因是弱化仅对于“读”、“写”操作的描述。“访问”一词的原意是“有目的地看望并交谈”，能够将查看和读写操作结合起来。不过技术层面上词典似乎更倾向于将其与“网络”结合起来解释。

**Comment by linenli** [comment]
建议“存档访问器”

根据前后文显示，这个模块支持使用者获取生命周期的相关事件，仅“快照”模式支持。看起来类似于UDS的freeze frame，或者游戏内的存档。使用“存档”可能更易联想到是对生命周期事件，随着系统运行产生事件的存储。”档案”比较容易想到和配置项相关的内容。

**Comment by y2-Whyto** [comment]
> 建议“存档访问器”
> 
> 
> 
> 根据前后文显示，这个模块支持使用者获取生命周期的相关事件，仅“快照”模式支持。看起来类似于UDS的freeze frame，或者游戏内的存档。使用“存档”可能更易联想到是对生命周期事件，随着系统运行产生事件的存储。”档案”比较容易想到和配置项相关的内容。

这里我想要说明一点，那就是“存档”本身是一个动宾短语，其中的“存”是一个动词，即“保存”，而“档”本身就是“档案”，如果考虑词类活用（动词用作名词），那么该词直接翻译也是“保存下来的档案”，与“档案”一词区别不大，甚至“存”这个动作性的描述略显多余（毕竟能访问的档案基本上都是“存”下来的），所以我认为单纯用“档案”一词即可达意。

下面是“存档”一词在《现代汉语规范词典》中的解释（iOS内置）：

> 【动】把处理过的文件、资料、稿件等资料存入档案，以备参考。

**Comment by Sylsd** [comment]
”访问器“译法我同意，关于**Archive** 我提供另一个角度的看法：

**Archive** 日常使用时，多有动词和名词两种理解：
 - 做动词，把…存档；把…归档；
 - 做名词，档案文件；归档文件；档案馆；

故，当以名词形式译作**存档**或**归档**时，多是指 *该文件是不常用的，需要被归类存储起来的*。

综上所述，如果 **Lifecycle events** 是已经发生过的、未来不常用，被系统存储起来的内容， 我认为应该用“存档访问器”。

否则，则使用“档案访问器”。

**Comment by y2-Whyto** [comment]
> ”访问器“译法我同意，关于**Archive** 我提供另一个角度的看法：
> 
> **Archive** 日常使用时，多有动词和名词两种理解：
> 
> * 做动词，把…存档；把…归档；
> * 做名词，档案文件；归档文件；档案馆；
> 
> 故，当以名词形式译作**存档**或**归档**时，多是指 _该文件是不常用的，需要被归类存储起来的_。
> 
> 综上所述，如果 **Lifecycle events** 是已经发生过的、未来不常用，被系统存储起来的内容， 我认为应该用“存档访问器”。
> 
> 否则，则使用“档案访问器”。

如同我上面所做的回复，在此我想再详细地讨论一下 archive 这个词，顺便讨论一下您所提及的“过去”、“少用”的特点。

根据[剑桥词典](https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%AE%80%E4%BD%93/archive)：

> ***noun*** [C]
> 1. a collection of **historical records** relating to a place, organization, or family. 档案；案卷。
> 1. a place where **historical records** are kept. 档案馆；档案室。
> 1. a computer file used to store electronic information or documents that you no longer need to use regularly.（计算机上保存文件的）档案。
>
> ***verb*** [T]
> in computer technology, to store electronic information that you no longer need to use regularly.（在计算机上将信息）存档。

根据 *New Oxford American Dictionary* 和《牛津英汉汉英词典》（macOS 内置）：

> **noun**
> a collection of **historical documents or records** providing information about a place, institution, or group of people. 档案。
> - the place where historical documents or records are kept. 档案馆。
> - a complete record of the data in part or all of a computer system, stored on an infrequently used medium.（该解释在英汉汉英词典中没有收录，可能与版本不同步有关）
>
> **verb** *[with object]* 
> place or store (something) in an archive. 把…存档。
> *Computing* transfer (data) to a less frequently used storage medium such as magnetic tape, typically external to the computer system and having a greater storage capacity. 把…存档。

首先我们要明确该合成词中的 archive 是什么词性，我想很明显是名词。如果难以理解，可以参考这样的表达：heart-breaker, SD card reader, etc.

那么，我们可以首先关注上述两个词典对于 archive 名词的解释，首先是 *New Oxford American Dictionary* 甚至直接收录了其计算机术语的义项，但是碍于没有直接的中文翻译，我们暂且不细看。而 archive 一词的本意核心围绕着一个东西：historical records/documents。它在中文里对应的翻译是“档案”。也就是说，**“档案”一词可以表示其“过去”的性质**。虽然“档案”在《现代汉语规范词典》中的解释如下（并未直接写明“过去”性质）：

> 【名】国家机关、社会组织及个人从事各种活动形成的需**保存下来以备查考**的文字材料和音像记录。

我们再看 archive 有关计算机术语的动词解释，虽然两本词典都体现了一个“less frequently”的含义，但是其中文翻译中依然使用的是“存**档**”的字眼。很明显，“存”负责解释“transfer to”、“store”的部分，而不论我们把“存档”一词补充成“保存档案”还是“保存至档案”，也就是无论“档”对应的是宾语“data”、“information”还是状语（中的宾语）“to a less frequently used storage medium”，“档”都显然是对应了该词名词的部分。换言之，**“档”（即“档案”）一词能够体现出（如果非要强调的话）所谓的“少用”性质。**

而“存”本身就是在动词解释中才出现的动词部分，因此无论怎么理解，我认为都不必放在名词词性的翻译中（即使把“存”放进去，中心词还是“档案”）。**希望大家不要把“存档”这个词看得过于不可分。**
