### ISSUE TITLE
约定与术语表

### ISSUE THREAD

**Issue by Mr-Linus** [FuchsiaOS/FuchsiaOS-docs-zh_CN#7]
为了便于大家达成共识，以下为文档的翻译约定和词汇术语表。
## 格式
- 中文标点与英文之间不需要加空格
- 中文与数字之间、英文与数字之间都需要加空格。
- 出现并列的词请使用中文顿号
- 文章头信息中的description部分最后要以标点符号结束，如句号和问号

## 约定
- data 数据
- context 上下文
- hash 哈希
- read 读
- write 写
- client 客户端
- channel 信道
以下词汇不翻译：
- BookInfo
- Citadel
- HTTP header
- Mixer
- Network Policy 网络策略，如果特指 k8s 中的资源，建议不翻译
- Pilot
- TLS
- egress
- endpoint 端点，建议不翻译
- productpage 示例服务名，不用翻译
- ingress
- ratings 示例服务名，不用翻译
- reviews 示例服务名，不用翻译
- sidecar
如果大家对其他词汇有异议可以回复该issue。

**Comment by 1595901624** [comment]
在development/languages/fidl/reference中的 lex（下面使用黑体标示），应该是特指LEXical compiler，建议不翻译；
理由参见https://baike.baidu.com/item/lex/8558986?fr=aladdin

**Comment by iRoyHuang** [comment]
已经学习约定术语表，后续翻译将依据这个biao进行翻译。
