### ISSUE TITLE
如何翻译专有名词 pave

### ISSUE THREAD

**Issue by dongchany** [FuchsiaOS/FuchsiaOS-docs-zh_CN#70]
出现情况举例：
（下面的示例出现在 /development/build/build_and_pave_quickstart.md )

Before you attempt to build and **pave** Fuchsia on a target device, you need to
know the path of your USB drive.

牛津词典的解释：
VERB 动词铺[路或地面] If a road or an area of ground has been paved, it has been covered with flat blocks of stone or concrete, so that it is suitable for walking or driving on

目前采用的翻译是 **铺设**
pave：原则上是铺设的意思，很直接的。 但是中文并问没有对应的计算机语言。

当执行命令 `fx pave` 时它就是安装/铺设，这个是Fuchsia的一个新特性，原则上就是在你本机上编译构建好了镜像相关文件， fx pave 就把文件通过网络传输到目标设备上部署起来。 编译一次，到处运行。

**Comment by dongchany** [comment]
铺设

**Comment by chuyao** [comment]
结合语意，翻译成“配置”是否会“信达雅”一些？ build and pave，构建和配置。仅个人拙见，希望集思广益。

**Comment by dongchany** [comment]
> 结合语意，翻译成“配置”是否会“信达雅”一些？ build and pave，构建和配置。仅个人拙见，希望集思广益。

命令中 `fx set` 已经是 “配置”了，详情请看：https://fuchsia.dev/fuchsia-src/get-started/build_fuchsia

**Comment by wwvm** [comment]
传送，传输。这个过程是启动一个pave server，之后构建好的成品会被传送并更新到目标设备上。

**Comment by dongchany** [comment]
> 传送，传输。这个过程是启动一个pave server，之后构建好的成品会被传送并更新到目标设备上。

你说的这个“传送，传输”其实是`fx flash` ，详情：[What is Paving?](https://fuchsia.dev/fuchsia-src/development/build/fx#what-is-paving)

**Comment by dongchany** [comment]
The number of votes has been reached and merged into to 2021 branch.

**Comment by dongchany** [comment]
投票完成，合并到主分支上。
