### ISSUE TITLE
Fuchsia 入门文档中相关超链接点击皆出现Page Not Found

### ISSUE THREAD

**Issue by Submarinee** [FuchsiaOS/FuchsiaOS-docs-zh_CN#73]
在阅读[FuchsiaOS-docs-zh_CN/get-started/README.md](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/get-started/README.md)时，点击所有超链接后皆出现Page Not Found.

比如 『获取 Fuchsia 源代码』和『构建 Fuchsia』的超链接被点击后，出现Page Not Found。
只有我一个人存在这个问题吗？

**Comment by yang-lile** [comment]
`/docs/xxx` 下的目录就是本项目的入口目录，所以不用担心链接点击不了，保持不动就可以了

**Comment by Submarinee** [comment]
> `/docs/xxx` 下的目录就是本项目的入口目录，所以不用担心链接点击不了，保持不动就可以了

但是这个文档的超链接打不开，该文档不需要修改吗？

**Comment by dongchany** [comment]
> > `/docs/xxx` 下的目录就是本项目的入口目录，所以不用担心链接点击不了，保持不动就可以了
> 
> 但是这个文档的超链接打不开，该文档不需要修改吗？

修改好的PR, #79

**Comment by dongchany** [comment]
> > `/docs/xxx` 下的目录就是本项目的入口目录，所以不用担心链接点击不了，保持不动就可以了
> 
> 但是这个文档的超链接打不开，该文档不需要修改吗？

修改好的PR, #79
