### ISSUE TITLE
如何翻译compositor

### ISSUE THREAD

**Issue by yang-lile** [FuchsiaOS/FuchsiaOS-docs-zh_CN#74]
文件位置：
development/languages/rust/README.md

原文：
51 行：`Rust interface to Scenic, the Fuchsia compositor`

原译文：
Scenic 的 Rust 接口，Fuchsia作曲家

建议翻译：
Fuchsia 合成器 Scenic 的 Rust 接口

建议单词翻译：
compositor => 合成器

**Comment by yang-lile** [comment]
https://fuchsia.dev/fuchsia-src/concepts/graphics/scenic/scenic
这是官网文档位置

**Comment by chuyao** [comment]
> 
> 
> 文件位置：
> development/languages/rust/README.md
> 
> 原文：
> 51 行：`Rust interface to Scenic, the Fuchsia compositor`
> 
> 原译文：
> Scenic 的 Rust 接口，Fuchsia作曲家
> 
> 建议翻译：
> Fuchsia 合成器 Scenic 的 Rust 接口
> 
> 建议单词翻译：
> compositor => 合成器

非常感谢！当时确实也觉得很生硬，对这个单词熟悉和理解的程度不够，再查了下词典，确有“复合器、合成器”多义。会重新提pr，后续翻译也多多斟酌，向大佬学习。

**Comment by yang-lile** [comment]
没有没有，是我审核不及时的问题

**Comment by dongchany** [comment]
PR #78
