### ISSUE TITLE
如何翻译shard？它是专有名词吗？

### ISSUE THREAD

**Issue by Submarinee** [FuchsiaOS/FuchsiaOS-docs-zh_CN#82]
出现情况举例：
（下面的示例出现在 /concepts/components/v1/component_manifests.md中）
1.The optional `include` property describes zero or more other component manifest files (or **shards**) to be merged into this component manifest.
2.Includes can be recursive, meaning that **shards** can have their own includes.

**我想知道shard是否是一个专有名词？**
在Google Translate中，shard显示为“a piece of broken ceramic, metal, glass, or rock, typically having sharp edges”。
我目前采用的翻译是“**分片**”，
**我想问，翻译成“分片”是合适的吗？或者该词不需要翻译？**

**Comment by dongchany** [comment]
赞成分片。
我遇到的，这个词就是分片的意思。 数据库中的 Sharding MySQL 也是 分片的意思

**Comment by yang-lile** [comment]
那就采用分片一词吧，没有什么异议
