### ISSUE TITLE
如何翻译专有名词 LogSink

### ISSUE THREAD

**Issue by y2-Whyto** [FuchsiaOS/FuchsiaOS-docs-zh_CN#83]
出现情况举例：
（下面的示例出现在 `/concepts/diagnostics/logs/README.md`）
- If a message is written to the \[\`**LogSink**\`\] protocol it also has a severity, a
PID, a TID, a count of prior dropped logs, and a list of string tags.
- Unless a component's parent realm provides its own \`**LogSink**\`, diagnostics also
includes trusted \[SourceIdentity\] metadata for incoming log connections.

根据[官方的定义](https://fuchsia.dev/reference/fidl/fuchsia.logger#LogSink)：
> Drains a program's logs.（大意为“为程序日志引流”、“排出日志”）

“sink”的名词翻译，根据[剑桥词典](https://dictionary.cambridge.org/zhs/%E8%AF%8D%E5%85%B8/%E8%8B%B1%E8%AF%AD-%E6%B1%89%E8%AF%AD-%E7%AE%80%E4%BD%93/sink)：
> a bowl that is attached to the wall in a kitchen or bathroom in which you wash dishes or your hands, etc.（厨房的）洗涤槽，洗涤池；（浴室的）洗脸盆。

根据牛津英汉汉英词典（macOS内置）：
> 1. (basin) 洗碗槽 xǐwǎncáo
> 1. (cesspit) 污水坑 wūshuǐkēng
> 1. *before noun British* 污秽贫困地区的 wūhuì pínkùn dìqū de ‹estate›
> 1. *Technology* 汇 huì （这里这个术语下面的例子不是计算机学的，而是热力学、环境科学的）

**[Google Cloud 的官方文档](https://cloud.google.com/logging/docs/export#:~:text=%E5%A6%82%E9%9C%80%E8%AF%A6%E7%BB%86%E4%BA%86%E8%A7%A3%E6%8E%A5%E6%94%B6%E5%99%A8%EF%BC%8C%E8%AF%B7%E5%8F%82%E9%98%85%20LogSink%20%E7%B1%BB%E5%9E%8B%E3%80%82)中出现了该词，但是不译。而文档中对于“sink”的翻译采用了“接收器”。**

**我目前采用的翻译是“日志槽”。**

请大家针对可能的翻译畅所欲言。

**Comment by y2-Whyto** [comment]
日志槽

其实“水槽”和“水池”都有上面“引流”的意味，而使用“槽”而非“池”的主要原因在于“池”比较固定的、容易让人产生联想的翻译是“pool”，故舍之。

**Comment by y2-Whyto** [comment]
不译

**Comment by y2-Whyto** [comment]
日志接收器

**Comment by dongchany** [comment]
> 不译

LogSink 达到3个赞，可以录入。
