### ISSUE TITLE
如何翻译paving 和 amber

### ISSUE THREAD

**Issue by Sylsd** [FuchsiaOS/FuchsiaOS-docs-zh_CN#85]
## 原文

> [/gen/build_arguments.md#L312](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/3546767c107c42233ee746a6f0d2e71eea659c96/gen/build_arguments.md#L312)

Board name used for paving and amber updates.

## 待定翻译
| 单词/词组 | 释义 | 暂定翻译 | 备注 |
| -- | -- | -- | -- |
|paving  | 名词：a paved area, or material used to pave an area<br/> | paving | 参考关联文章1，**paving** 作为 Fuchsia 的专有安装过程的代称，应该保留原文。当pave以动词使用时，可以参考 #70 ，翻译为*铺设*。  |
| amber | 名词：琥珀（色）；<br/>形容词：琥珀（色）的 | amber | 参考关联文章3、4，**amber**作为 Fuchsia 更新系统的名称，应该保留原文。在当前 repo 中也未找到amber的其他用法。 |

## 关联文章及讨论
| 序号 | 出处 | 内容 | 备注 |
| -- | -- | -- | -- |
| 1 | [/development/hardware/paving.md#L4](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/3546767c107c42233ee746a6f0d2e71eea659c96/development/hardware/paving.md#L4) | The Fuchsia install process, called **'paving'**, requires two machines | -- |
| 2 | [/development/idk/documentation/ssh.md#L22](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/3546767c107c42233ee746a6f0d2e71eea659c96/development/idk/documentation/ssh.md#L22) | Follow the instruction for **paving** the target device | -- |
| 3 | [/development/idk/documentation/packages.md#L32](https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/3546767c107c42233ee746a6f0d2e71eea659c96/development/idk/documentation/packages.md#L32)| By default, this starts an **amber** server on the host machine at port `8083`. | -- |
| 4 | [Fuchsia OS –未来的Google操作系统](https://segmentfault.com/a/1190000038447862#:~:text=%E5%92%8C%E6%9B%B4%E6%96%B0%E7%B3%BB%E7%BB%9F-,Amber,-%E4%BB%A5%E5%8F%8A%E6%96%87%E6%9C%AC%E5%92%8C) | Garnet包含图形渲染器Escher，程序包管理和更新系统**Amber**以及文本和代码编辑器Xi。 | -- |
| 5 | #70  如何翻译专有名词pave | 投票通过，**pave**翻译为**铺设** | -- |

## 其他

> 1. 为避免文本修改，导致原文指向失效，所有github文章链接都加入了commit id。

**Comment by Sylsd** [comment]
建议翻译：
-  paving：paving（保留原文，pave表示动作时，参考 #70 ，）翻译为**铺设**
- amber：amber （保留原文）

**Comment by y2-Whyto** [comment]
用于铺设和 amber 更新的板型名称。

pave 和 paving 是同一个动作，词性不同，我建议都翻译成“铺设”。可以考虑我们在使用“安装”一词时，它既可以是动词性，也可以活用成名词性，比如“安装遇到问题，请稍后再试”中的“安装”即为名词，而实际上并不在句中加以区分。既然“铺设”和“安装”两个词地位和意义相同，那么“铺设”理应可以有这样的用法，在实际出现混淆情况时，可以参考“安装过程”的说法使用“铺设过程”。（当然实际加的到底是“过程”还是“动作”要看具体意思）

另外就是，个人感觉一个东西一会儿翻译一会儿不翻译似乎也有点奇怪呢..
