### ISSUE TITLE
文档中出现的文本编辑器菜单操作，英文菜单是否需要翻译？

### ISSUE THREAD

**Issue by chuyao** [FuchsiaOS/FuchsiaOS-docs-zh_CN#87]
### 问题描述：
> Note: To access the VS Code Workspace settings, click the View menu, then Command Palette, and select Preferences: Open Workspace Settings (JSON).

这段文档介绍了 VS Code 编辑器打开工作空间设置的操作步骤，涉及了编辑器的菜单操作，这些菜单的名称 `View` ， `Command Palette`， `Preferences: Open Workspace Settings (JSON)`，是否应该翻译成中文 `查看`， `命令面板`， `首选项：打开工作区设置（JSON）`？

### 疑惑的地方：
- VS Code 的默认语言是英文，英文菜单可以理解是专有名词
- VS Code 提供了官方中文扩展，可以将编辑器菜单汉化，有对应的官方中文翻译

也在TG上做过初步的讨论，大致三种意见：
- 保留英文名称，编辑器默认专有名词
- 翻译成中文，有对应惯用词
- 翻译成中文，用括号保留英文名称，如 `查看（View）`

除此之外，是否有更好的意见，可以为后面翻译的童鞋作参考？

[rust-editor]: https://github.com/FuchsiaOS/FuchsiaOS-docs-zh_CN/blob/2021/development/languages/rust/editors.md#rust-analyzer-vscode-extension-supported-workflow

**Comment by y2-Whyto** [comment]
翻译成中文，在括号内保留英文原文

**Comment by y2-Whyto** [comment]
仅翻译为中文

**Comment by y2-Whyto** [comment]
不译

**Comment by dongchany** [comment]
> 翻译成中文，在括号内保留英文原文

达到指定的赞数，关闭Issue
